### PR TITLE
Support for Symfony 4

### PR DESCRIPTION
**Pull request by Nyholm**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by asm89** [comment]
LGTM, travis is red. :(

**Comment by Nyholm** [comment]
Travis is much happier now. I've make sure we test on all Symfony versions we support.

**Comment by srt4rulez** [comment]
Can we get this merged in?

**Review by danshumaker — APPROVED** [review]

**Comment by danshumaker** [comment]
These changes are necessary for it to work with Drupal 9 - since drupal core is pinned to symfony/console ^4.

**Comment by bronzehedwick** [comment]
Would love to see this merged. Any movement here?

**Comment by asm89** [comment]
I guess the CI setup is out of date by now, but let's merge it.

**Pull request merged**
